# Generated by Django 5.2.17 on 2026-09-26 17:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libraries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(
                    default=uuid.uuid4,
                    editable=False,
                    primary_key=True,
                    serialize=False
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('next_due_date', models.DateField()),
                ('status', models.CharField(
                    choices=[
                        ('active', 'Active'),
                        ('due', 'Due'),
                        ('overdue', 'Overdue'),
                        ('archived', 'Archived')
                    ],
                    default='active',
                    max_length=20
                )),
                ('library', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='memberships',
                    to='libraries.library'
                )),
                ('plan', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='memberships',
                    to='libraries.pricingplan'
                )),
                ('seat', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='memberships',
                    to='seats.seat'
                )),
                ('student', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='memberships',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'abstract': False,
            },
        ),
    ]