# Generated by Django 5.2.17 on 2026-09-30 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_membership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='student',
            new_name='recipient',
        ),
    ]
