# Generated by Django 5.2.17 on 2026-10-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_rename_student_notification_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
