# Generated by Django 6.1.1 on 2026-09-26 12:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libraries', '0002_alter_library_options_alter_pricingplan_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('empty', 'Empty'), ('reserved', 'Reserved'), ('occupied', 'Occupied')], default='empty', max_length=10)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='libraries.library')),
            ],
            options={
                'ordering': ['label'],
                'unique_together': {('library', 'label')},
            },
        ),
    ]
