# Generated by Django 5.2.17 on 2026-10-01 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('memberships', '0001_initial'),
        ('payments', '0002_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='memberships.membership'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='bookings.booking'),
        ),
    ]
