# Generated by Django 6.1.1 on 2026-09-26 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'verbose_name_plural': 'libraries'},
        ),
        migrations.AlterModelOptions(
            name='pricingplan',
            options={'ordering': ['duration_days', 'price']},
        ),
        migrations.AddField(
            model_name='library',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='operating_hours',
            field=models.CharField(blank=True, help_text='e.g. 08:00 AM - 10:00 PM', max_length=100),
        ),
        migrations.AddField(
            model_name='library',
            name='total_seats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='library',
            name='closes_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='library',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='library',
            name='opens_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='library', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
